const CURRENCIES = {
	USD: { name: "US Dollar", symbol: "$" },
	EUR: { name: "Euro", symbol: "€" },
	INR: { name: "Indian Rupee", symbol: "₹" },
	GBP: { name: "British Pound Sterling", symbol: "£" },
	JPY: { name: "Japanese Yen", symbol: "¥" },
	CNY: { name: "Chinese Yuan", symbol: "CN¥" },
	AUD: { name: "Australian Dollar", symbol: "AU$" },
	CAD: { name: "Canadian Dollar", symbol: "CA$" },
	AED: { name: "United Arab Emirates Dirham", symbol: "AED" },
	AFN: { name: "Afghan Afghani", symbol: "Af" },
	ALL: { name: "Albanian Lek", symbol: "ALL" },
	AMD: { name: "Armenian Dram", symbol: "AMD" },
	ANG: { name: "Netherlands Antillean Guilder", symbol: "ANG" },
	AOA: { name: "Angolan Kwanza", symbol: "AOA" },
	ARS: { name: "Argentine Peso", symbol: "AR$" },
	AZN: { name: "Azerbaijani Manat", symbol: "man." },
	BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
	BDT: { name: "Bangladeshi Taka", symbol: "Tk" },
	BGN: { name: "Bulgarian Lev", symbol: "BGN" },
	BHD: { name: "Bahraini Dinar", symbol: "BD" },
	BIF: { name: "Burundian Franc", symbol: "FBu" },
	BMD: { name: "Bermudian Dollar", symbol: "BMD" },
	BND: { name: "Brunei Dollar", symbol: "BN$" },
	BOB: { name: "Bolivian Boliviano", symbol: "Bs" },
	BRL: { name: "Brazilian Real", symbol: "R$" },
	BWP: { name: "Botswanan Pula", symbol: "BWP" },
	BYN: { name: "Belarusian Ruble", symbol: "Br" },
	BZD: { name: "Belize Dollar", symbol: "BZ$" },
	CDF: { name: "Congolese Franc", symbol: "CDF" },
	CHF: { name: "Swiss Franc", symbol: "CHF" },
	CLP: { name: "Chilean Peso", symbol: "CL$" },
	COP: { name: "Colombian Peso", symbol: "CO$" },
	CRC: { name: "Costa Rican Colón", symbol: "₡" },
	CZK: { name: "Czech Republic Koruna", symbol: "Kč" },
	DJF: { name: "Djiboutian Franc", symbol: "Fdj" },
	DKK: { name: "Danish Krone", symbol: "Dkr" },
	DOP: { name: "Dominican Peso", symbol: "RD$" },
	DZD: { name: "Algerian Dinar", symbol: "DA" },
	EGP: { name: "Egyptian Pound", symbol: "EGP" },
	ETB: { name: "Ethiopian Birr", symbol: "Br" },
	GEL: { name: "Georgian Lari", symbol: "GEL" },
	GHS: { name: "Ghanaian Cedi", symbol: "GH₵" },
	GNF: { name: "Guinean Franc", symbol: "FG" },
	GTQ: { name: "Guatemalan Quetzal", symbol: "GTQ" },
	HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
	HNL: { name: "Honduran Lempira", symbol: "HNL" },
	HRK: { name: "Croatian Kuna", symbol: "kn" },
	HUF: { name: "Hungarian Forint", symbol: "Ft" },
	IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
	ILS: { name: "Israeli New Sheqel", symbol: "₪" },
	IQD: { name: "Iraqi Dinar", symbol: "IQD" },
	IRR: { name: "Iranian Rial", symbol: "IRR" },
	ISK: { name: "Icelandic Króna", symbol: "Ikr" },
	JMD: { name: "Jamaican Dollar", symbol: "J$" },
	JOD: { name: "Jordanian Dinar", symbol: "JD" },
	KES: { name: "Kenyan Shilling", symbol: "Ksh" },
	KHR: { name: "Cambodian Riel", symbol: "KHR" },
	KRW: { name: "South Korean Won", symbol: "₩" },
	KWD: { name: "Kuwaiti Dinar", symbol: "KD" },
	KZT: { name: "Kazakhstani Tenge", symbol: "KZT" },
	LBP: { name: "Lebanese Pound", symbol: "L.L." },
	LKR: { name: "Sri Lankan Rupee", symbol: "SLRs" },
	MAD: { name: "Moroccan Dirham", symbol: "MAD" },
	MDL: { name: "Moldovan Leu", symbol: "MDL" },
	MMK: { name: "Myanma Kyat", symbol: "MMK" },
	MXN: { name: "Mexican Peso", symbol: "MX$" },
	MYR: { name: "Malaysian Ringgit", symbol: "RM" },
	NAD: { name: "Namibian Dollar", symbol: "N$" },
	NGN: { name: "Nigerian Naira", symbol: "₦" },
	NOK: { name: "Norwegian Krone", symbol: "Nkr" },
	NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
	OMR: { name: "Omani Rial", symbol: "OMR" },
	PEN: { name: "Peruvian Nuevo Sol", symbol: "S/." },
	PHP: { name: "Philippine Peso", symbol: "₱" },
	PKR: { name: "Pakistani Rupee", symbol: "PKRs" },
	PLN: { name: "Polish Zloty", symbol: "zł" },
	QAR: { name: "Qatari Rial", symbol: "QR" },
	RON: { name: "Romanian Leu", symbol: "RON" },
	RSD: { name: "Serbian Dinar", symbol: "din." },
	RUB: { name: "Russian Ruble", symbol: "RUB" },
	SAR: { name: "Saudi Riyal", symbol: "SR" },
	SEK: { name: "Swedish Krona", symbol: "Skr" },
	SGD: { name: "Singapore Dollar", symbol: "S$" },
	THB: { name: "Thai Baht", symbol: "฿" },
	TRY: { name: "Turkish Lira", symbol: "TL" },
	UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
	UGX: { name: "Ugandan Shilling", symbol: "USh" },
	VND: { name: "Vietnamese Dong", symbol: "₫" },
	XAF: { name: "CFA Franc BEAC", symbol: "FCFA" },
	XOF: { name: "CFA Franc BCEAO", symbol: "CFA" },
	ZAR: { name: "South African Rand", symbol: "R" },
	ZMW: { name: "Zambian Kwacha", symbol: "ZK" },
};

const CURRENCY_CODES = Object.keys(CURRENCIES);

module.exports = {
	CURRENCIES,
	CURRENCY_CODES,
};
